[tool.bumpversion]
current_version = "0.4.35"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = true
commit = true
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[[tool.bumpversion.files]]
filename = "DESCRIPTION"
search = 'Version: {current_version}'
replace = "Version: {new_version}"
regex = true

[[tool.bumpversion.files]]
filename = "README.md"
search = 'tag = "v{current_version}"'
replace = 'tag = "v{new_version}"'
regex = true
