[project]
name = "disize"
r_version = "4.5"

# any CRAN-type repository, order matters. Additional ability to force source package installation
# Example: {alias = "CRAN", url = "https://cran.r-project.org", force_source = true}
repositories = [
    { alias = "CRAN", url = "https://cran.r-project.org" },
    { alias = "STAN", url = "https://stan-dev.r-universe.dev" },
    { alias = "BIOC-PAC", url = "https://bioconductor.org/packages/3.21/bioc" },
    { alias = "BIOC-ANN", url = "https://bioconductor.org/packages/3.21/data/annotation" },
    { alias = "BIOC-EXP", url = "https://bioconductor.org/packages/3.21/data/experiment" },
]

# package to install and any specifications. Any descriptive dependency can have the `install_suggestions` specification
# Examples:
# "dplyr",
# {name = "dplyr", repository = "CRAN", force_source = true},
# {name = "dplyr", git = "https://github.com/tidyverse/dplyr.git", tag = "v1.1.4"},
# {name = "dplyr", path = "/path/to/local/dplyr"},
dependencies = [
    "reshape2",
    "devtools",
    "testthat",
    "progress",
    "reformulas",
    { name = "cmdstanr", repository = "STAN" },
    "instantiate",
    "dplyr",
    "tidyr",
    "purrr",
    "R.utils",
    "rmarkdown",
    "pandoc",
    "pasilla",
    "edgeR",
    "future",
    "future.apply",
]
